# # encoding: utf-8

# Inspec test for recipe pulp-server-cookbook::admin

# The Inspec reference, with examples and extensive documentation, can be
# found at http://inspec.io/docs/reference/resources/

describe file('/etc/pulp/admin/admin.conf') do
  it { should be_file }
  it { should be_owned_by 'root' }
  it { should be_grouped_into 'root' }
  its('mode') { should cmp '0644' }
  its('content') { should match(/This file was generated by Chef/) }
end

describe command('pulp-admin login -u admin -p admin') do
  its('exit_status') { should eq 0 }
end
